name: Build Documentation
description: 'Build Documentation.'

runs:
  using: composite
  steps:
    - name: Install documentation gems
      shell: bash
      run: bundle install

    - name: Build Documentation
      shell: bash
      run: bundle exec jazzy -o docs
