name: Lint
description: 'Run podspec and swiftlint checks.'

runs:
  using: composite
  steps:
    - name: Install mint
      shell: bash
      run: brew install mint

    - name: Install swift lint
      shell: bash
      run: brew install swiftlint

    - name: Bootstrap mint packages
      shell: bash
      run: mint bootstrap

    - name: Install cocoapods
      shell: bash
      run: gem install cocoapods

    - name: Lint the podspec
      shell: bash
      run: pod lib lint LaunchDarkly.podspec --allow-warnings

    - name: Run swiftlint
      shell: bash
      run: |
        cd ./ContractTests
        swiftlint lint
