name: Run CI
on:
  push:
    branches: [ v11, 'feat/**' ]
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [ v11, 'feat/**' ]
    paths-ignore:
      - '**.md'

jobs:
  lint:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
        with:
          xcode-version: 16.4.0

      - uses: ./.github/actions/lint

  build-ios:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode-version: 16.4.0
            ios-sim: "platform=iOS Simulator,name=iPhone 16"
            os: macos-15
          - xcode-version: 15.4.0
            ios-sim: "platform=iOS Simulator,name=iPhone 15"
            os: macos-14

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
        with:
          xcode-version: ${{ matrix.xcode-version }}

      - uses: ./.github/actions/build-ios
        with:
          ios-sim: ${{ matrix.ios-sim }}

  build-macos:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode-version: 16.4.0
            os: macos-15
          - xcode-version: 15.4.0
            os: macos-14

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
        with:
          xcode-version: ${{ matrix.xcode-version }}

      - uses: ./.github/actions/build-macos

  build-tvos:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode-version: 16.4.0
            os: macos-15
          - xcode-version: 15.4.0
            os: macos-14

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
        with:
          xcode-version: ${{ matrix.xcode-version }}

      - uses: ./.github/actions/build-tvos

  build-watchos:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode-version: 16.4.0
            os: macos-15
          - xcode-version: 15.4.0
            os: macos-14

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
        with:
          xcode-version: ${{ matrix.xcode-version }}

      - uses: ./.github/actions/build-watchos

  test-swiftpm:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode-version: 16.4.0
            os: macos-15
          - xcode-version: 15.4.0
            os: macos-14

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
        with:
          xcode-version: ${{ matrix.xcode-version }}

      - uses: ./.github/actions/test-swiftpm

  contract-tests:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
        with:
          xcode-version: 16.4.0

      - uses: ./.github/actions/contract-tests
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build-docs:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
        with:
          xcode-version: 16.4.0

      - uses: ./.github/actions/build-docs
